#!/usr/bin/env python3
"""Validate the generated SIBurst site in docs/.

Checks generation integrity, runtime surface, structure, claim boundary,
fixture integration, the static fallback, runtime constraints, contrast, and
size budgets. Standard library only (the generation check calls the build,
which needs the pinned build dependency). Fails closed.

Usage:
    python tools/validate_site.py [--docs DIR] [--skip-build-check]
"""

import argparse
import gzip
import json
import os
import re
import sys
from collections import namedtuple
from html.parser import HTMLParser
from urllib.parse import urlsplit

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO_ROOT, "tools"))

import build_site  # noqa: E402

DOCS = os.path.join(REPO_ROOT, "docs")
SRC = os.path.join(REPO_ROOT, "src", "site")
FIXTURE = os.path.join(REPO_ROOT, "data", "demonstration-fixture.json")
STAGES = build_site.STAGES
ALLOWED_EXTERNAL_LINKS = ("https://github.com/Sohadot/SIBurst",)
ALLOWED_EXTERNAL_META = ("https://siburst.com/",)
SCOPE = "SYSTEM DEMONSTRATION — a model of the SIBurst concept, not a measurement."

# Budgets (INTERFACE_CONTRACT.md section 8), in compressed bytes.
JS_BUDGET = 30 * 1024
FIRST_VIEW_BUDGET = 150 * 1024

# Minimum contrast (VISUAL_SYSTEM.md section 2): (foreground, background, minimum, use).
CONTRAST_PAIRS = [
    ("--color-primary", "--color-background", 4.5, "primary text"),
    ("--color-secondary", "--color-background", 4.5, "secondary text"),
    ("--color-threshold", "--color-background", 4.5, "threshold readout text and stubs"),
    ("--color-post-transition", "--color-background", 4.5, "post-transition links and nodes"),
    ("--color-signal-active", "--color-background", 3.0, "active signal graphics"),
    ("--color-signal-dormant", "--color-background", 3.0, "dormant signal graphics"),
    ("--color-structure", "--color-background", 3.0, "rails, boundary, receded field"),
    ("--color-focus", "--color-background", 3.0, "focus indicator"),
]

RUNTIME_FORBIDDEN = [
    (r"Math\.random", "randomness"),
    (r"\bsetInterval\s*\(", "interval timer"),
    (r"webgl|WebGLRenderingContext", "WebGL"),
    (r"getContext\s*\(", "canvas rendering"),
    (r"<canvas\b", "canvas element"),
    (r"\bTHREE\.", "three.js"),
    (r"\bd3\.", "d3"),
    (r"\bgsap\b", "GSAP"),
    (r"\bReact\b|react-dom", "React"),
    (r"\bVue\b|createApp\s*\(", "Vue"),
    (r"\bsvelte\b", "Svelte"),
    (r"\bjQuery\b|\$\(\s*document", "jQuery"),
    (r"\bgtag\b|google-analytics|googletagmanager", "analytics"),
    (r"\bmixpanel\b|\bhotjar\b|cdn\.segment|segment\.com|\banalytics\.js", "analytics"),
    (r"forceSimulation|forceLink|forceManyBody", "force simulation"),
    (r"document\.cookie|localStorage|sessionStorage", "client storage"),
    (r"navigator\.sendBeacon|XMLHttpRequest|WebSocket|EventSource", "network API"),
]
CLAIM_FORBIDDEN = [
    r"\bLIVE\b", r"REAL-TIME", r"\bCURRENT AI\b", r"\bAGI STATUS\b", r"\bSI LEVEL\b",
    r"INTELLIGENCE SCORE", r"superintelligence is here", r"singularity (begins|is here)",
    r"crossed the threshold", r"breakthrough achieved",
]
PRIVATE_TERMS = [
    r"\bpricing\b", r"\bprice\b", r"\bvaluation\b", r"\bbuyers?\b", r"\bnegotiat", r"\boutreach\b",
    r"\bportfolio\b", r"\brenewal\b", r"\bconfidential\b", r"claude\.ai/code", r"\bsession_[A-Za-z0-9]",
    r"Generated by \[?Claude", r"Co-Authored-By",
]
VOLATILE = [r"/home/", r"/tmp/", r"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}", r"\bgenerated_at\b"]

Failure = namedtuple("Failure", "invariant subject detail")


class Page(HTMLParser):
    """Collects the elements the validator reasons about."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.elements = []  # (tag, attrs dict)
        self.ids = set()
        self.text = []
        self._skip = 0
        self.stack = []
        self.stage_text = {}

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        self.elements.append((tag, a))
        if "id" in a:
            self.ids.add(a["id"])
        if tag in ("script", "style"):
            self._skip += 1
        self.stack.append((tag, a))

    def handle_startendtag(self, tag, attrs):
        a = dict(attrs)
        self.elements.append((tag, a))
        if "id" in a:
            self.ids.add(a["id"])

    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self._skip = max(0, self._skip - 1)
        while self.stack:
            t, _ = self.stack.pop()
            if t == tag:
                break

    def handle_data(self, data):
        if not self._skip:
            self.text.append(data)


def parse(path):
    page = Page()
    with open(path, "rb") as handle:
        page.feed(handle.read().decode("utf-8"))
    return page


def read_bytes(path):
    with open(path, "rb") as handle:
        return handle.read()


def gz(data):
    return len(gzip.compress(data, compresslevel=9, mtime=0))


def luminance(hex_color):
    h = hex_color.lstrip("#")
    channels = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    linear = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(a, b):
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def css_variables(css):
    root = re.search(r":root\s*\{(.*?)\}", css, re.S)
    if not root:
        return {}
    return dict(re.findall(r"(--[\w-]+)\s*:\s*(#[0-9A-Fa-f]{6})\s*;", root.group(1)))


class SiteValidator:
    def __init__(self, docs=DOCS, build_check=True):
        self.docs = docs
        self.build_check = build_check
        self.failures = []
        self.report = {}

    def fail(self, invariant, subject, detail):
        self.failures.append(Failure(invariant, subject, detail))

    def html_files(self):
        out = []
        for base, dirs, names in os.walk(self.docs):
            dirs.sort()
            for name in sorted(names):
                if name.endswith(".html"):
                    out.append(os.path.join(base, name))
        return out

    # -- Generation integrity ------------------------------------------------

    def generation(self):
        if self.build_check:
            for problem in build_site.check(self.docs):
                self.fail("generation.drift", "docs/", problem)
        public = os.path.join(self.docs, "data", "demonstration-fixture.json")
        if not os.path.exists(public) or read_bytes(public) != read_bytes(FIXTURE):
            self.fail("fixture.copy", "docs/data/demonstration-fixture.json", "not byte-identical to data/demonstration-fixture.json")
        for asset in ("system.css", "system.js"):
            target = os.path.join(self.docs, "assets", asset)
            if not os.path.exists(target) or read_bytes(target) != read_bytes(os.path.join(SRC, "assets", asset)):
                self.fail("generation.asset", "docs/assets/" + asset, "not byte-identical to src/site/assets/" + asset)
        for base, _, names in os.walk(self.docs):
            for name in names:
                text = read_bytes(os.path.join(base, name)).decode("utf-8", "replace")
                for pattern in VOLATILE:
                    if re.search(pattern, text):
                        self.fail("generation.volatile", os.path.relpath(os.path.join(base, name), self.docs), pattern)

    # -- Runtime surface -----------------------------------------------------

    def surface(self):
        for path in self.html_files():
            rel = os.path.relpath(path, self.docs)
            page = parse(path)
            for tag, a in page.elements:
                if tag == "script":
                    src = a.get("src")
                    if not src:
                        self.fail("runtime.inline_script", rel, "inline <script> is not allowed")
                    elif urlsplit(src).scheme or src.startswith("//"):
                        self.fail("runtime.external_script", rel, src)
                if tag == "link":
                    href = a.get("href", "")
                    rel_attr = a.get("rel", "")
                    external = urlsplit(href).scheme or href.startswith("//")
                    if rel_attr == "canonical":
                        if not href.startswith(ALLOWED_EXTERNAL_META):
                            self.fail("runtime.external_link", rel, href)
                    elif external:
                        self.fail("runtime.external_stylesheet" if "stylesheet" in rel_attr else "runtime.external_resource", rel, href)
                    if rel_attr in ("preload", "prefetch", "preconnect", "dns-prefetch", "modulepreload") and external:
                        self.fail("runtime.external_resource", rel, href)
                if tag in ("iframe", "frame", "object", "embed", "form", "canvas", "video", "audio"):
                    self.fail("runtime.forbidden_element", rel, "<%s>" % tag)
                if tag == "img":
                    src = a.get("src", "")
                    if urlsplit(src).scheme or src.startswith("//"):
                        self.fail("runtime.tracking_pixel", rel, src)
                if tag == "style":
                    self.fail("runtime.inline_style", rel, "<style> element is not allowed under the CSP")
                if "style" in a:
                    self.fail("runtime.inline_style", rel, "style attribute on <%s>" % tag)
                if tag == "meta" and a.get("property", "").startswith("og:url") and not a.get("content", "").startswith(ALLOWED_EXTERNAL_META):
                    self.fail("runtime.external_link", rel, a.get("content"))
                if tag == "a":
                    href = a.get("href", "")
                    if (urlsplit(href).scheme or href.startswith("//")) and not href.startswith(ALLOWED_EXTERNAL_LINKS):
                        self.fail("runtime.external_link", rel, href)
            csp = [a.get("content", "") for t, a in page.elements if t == "meta" and a.get("http-equiv", "").lower() == "content-security-policy"]
            if not csp:
                self.fail("runtime.csp", rel, "missing Content-Security-Policy")
            else:
                policy = csp[0]
                for directive in ("default-src 'none'", "object-src 'none'", "base-uri 'none'", "form-action 'none'", "font-src 'none'"):
                    if directive not in policy:
                        self.fail("runtime.csp", rel, "missing %s" % directive)
                if "unsafe-inline" in policy or "unsafe-eval" in policy or re.search(r"https?:", policy):
                    self.fail("runtime.csp", rel, "policy weakened: %s" % policy)
        css = read_bytes(os.path.join(self.docs, "assets", "system.css")).decode("utf-8")
        if re.search(r"@import|@font-face|url\(", css):
            self.fail("runtime.external_font", "assets/system.css", "@import, @font-face or url() is not allowed")
        for name in ("assets/system.js", "assets/system.css", "index.html"):
            text = read_bytes(os.path.join(self.docs, name)).decode("utf-8")
            for pattern, label in RUNTIME_FORBIDDEN:
                if re.search(pattern, text, re.I if label not in ("React", "Vue", "jQuery", "three.js") else 0):
                    self.fail("runtime.dependency", name, "%s (%s)" % (label, pattern))
            for match in re.findall(r"""(?:https?:)?//[^\s"'`)<>]+""", text):
                if not match.startswith(ALLOWED_EXTERNAL_LINKS + ALLOWED_EXTERNAL_META + ("http://www.w3.org/2000/svg",)):
                    self.fail("runtime.remote_reference", name, match)

    # -- Structure and links -------------------------------------------------

    def structure(self):
        index_path = os.path.join(self.docs, "index.html")
        if not os.path.exists(index_path):
            self.fail("structure.index", "index.html", "missing")
            return
        page = parse(index_path)
        self.index = page
        sections = [(a.get("id"), a.get("data-stage")) for t, a in page.elements if t == "section" and "stage" in a.get("class", "").split()]
        expected = [(s.lower(), s) for s in STAGES]
        if sections != expected:
            self.fail("structure.stages", "index.html", "expected stage sections %s, found %s" % (expected, sections))
        for fragment in [s.lower() for s in STAGES] + ["reference"]:
            if fragment not in page.ids:
                self.fail("structure.fragment", "index.html", "#%s missing" % fragment)
        nav = [a.get("href") for t, a in page.elements if t == "a" and a.get("data-stage-link")]
        if nav != ["#%s" % s.lower() for s in STAGES]:
            self.fail("structure.stage_nav", "index.html", "stage navigation %s" % nav)
        focusable = [a for t, a in page.elements if t in ("a", "button") and (t != "a" or a.get("href"))]
        if not focusable or focusable[0].get("href") != "#reference" or "skip-link" not in focusable[0].get("class", ""):
            self.fail("structure.skip_link", "index.html", "first focusable element must be the skip-to-reference link")
        for required in ("demonstration", "readout", "stage-announcer"):
            if required not in page.ids:
                self.fail("structure.panel", "index.html", "#%s missing" % required)
        live = [a for t, a in page.elements if a.get("id") == "stage-announcer"]
        if live and live[0].get("aria-live") != "polite":
            self.fail("structure.live_region", "index.html", "stage announcer must be aria-live=polite")
        for t, a in page.elements:
            if t == "svg" and a.get("aria-hidden") != "true":
                self.fail("structure.svg_hidden", "index.html", "demonstration graphics must be aria-hidden")
        expected_pages = ["index.html"] + [build_site.slug_for(n) for n in build_site.REFERENCE_FILES]
        for name in expected_pages:
            if not os.path.exists(os.path.join(self.docs, "reference", name)):
                self.fail("structure.reference_page", "reference/" + name, "missing")
        self.report["reference_pages"] = len(expected_pages) - 1
        self.links()

    def links(self):
        pages = {os.path.relpath(p, self.docs).replace(os.sep, "/"): parse(p) for p in self.html_files()}
        checked = 0
        for rel, page in pages.items():
            for tag, a in page.elements:
                target = a.get("href") if tag in ("a", "link") else a.get("src") if tag == "script" else None
                if not target or urlsplit(target).scheme or target.startswith("//"):
                    continue
                path, _, fragment = target.partition("#")
                base = os.path.dirname(rel)
                resolved = os.path.normpath(os.path.join(base, path)).replace(os.sep, "/") if path else rel
                if resolved.endswith("/") or os.path.isdir(os.path.join(self.docs, resolved)) or resolved == ".":
                    resolved = os.path.normpath(os.path.join(resolved, "index.html")).replace(os.sep, "/")
                checked += 1
                if not os.path.exists(os.path.join(self.docs, resolved)):
                    self.fail("links.broken", rel, "%s -> %s" % (target, resolved))
                    continue
                if fragment and resolved.endswith(".html") and fragment not in pages[resolved].ids:
                    self.fail("links.broken_fragment", rel, target)
        self.report["local_links_checked"] = checked

    # -- Claim boundary --------------------------------------------------------

    def claims(self):
        page = getattr(self, "index", None)
        if page is None:
            return
        raw = read_bytes(os.path.join(self.docs, "index.html")).decode("utf-8")
        visible = " ".join(" ".join(page.text).split())
        if raw.count(SCOPE) < 1 + len(STAGES):
            self.fail("claims.scope", "index.html", "demonstration scope statement must appear in the panel and in every stage figure")
        if "%" in visible:
            self.fail("claims.percentage", "index.html", "visible text contains a percentage")
        for pattern in CLAIM_FORBIDDEN:
            for name in ("index.html", "assets/system.js"):
                text = visible if name == "index.html" else read_bytes(os.path.join(self.docs, name)).decode("utf-8")
                if re.search(pattern, text, re.I if pattern.islower() else 0):
                    self.fail("claims.wording", name, pattern)
        fixture = json.loads(read_bytes(FIXTURE).decode("utf-8"))
        labels = {s["id"]: s["state_label"] for s in fixture["stages"]}
        for s in STAGES:
            expected = "DEMONSTRATION STATE · %s / %s" % (s, labels[s])
            section = re.search(r'<section class="stage" id="%s".*?</section>' % s.lower(), raw, re.S)
            if not section or expected not in section.group(0):
                self.fail("claims.stage_label", s, "readout must read %r" % expected)

    # -- Fixture integration and static fallback ------------------------------

    def fixture_integration(self):
        fixture = json.loads(read_bytes(FIXTURE).decode("utf-8"))
        anchors = sorted(e["id"] for e in fixture["entities"] if e["anchor"])
        derived = {row["stage"]: row for row in fixture["derived"]}
        graph_literal = re.compile(r"\bN(0[1-9]|1\d|2[0-4])\b|\bR\d{2}\b|\"C[1-4]\"")
        for name in ("assets/system.js", "assets/system.css"):
            if graph_literal.search(read_bytes(os.path.join(SRC, name)).decode("utf-8")):
                self.fail("fixture.second_graph", "src/site/" + name, "contains entity, relationship or cluster literals")
        for name in os.listdir(SRC):
            if name.endswith(".html") and graph_literal.search(read_bytes(os.path.join(SRC, name)).decode("utf-8")):
                self.fail("fixture.second_graph", "src/site/" + name, "template contains graph literals")
        raw = read_bytes(os.path.join(self.docs, "index.html")).decode("utf-8")

        def svgs(fragment):
            return re.findall(r'<svg class="(?:system|record)"[^>]*data-layout="(\w+)"[^>]*>(.*?)</svg>', fragment, re.S)

        expectations = {"S0": 3, "S1": 15, "S2": 22, "S3": 24, "S4": 24, "S5": 24, "S6": 24}
        for s in STAGES:
            section = re.search(r'<section class="stage" id="%s".*?</section>' % s.lower(), raw, re.S)
            if not section:
                continue
            figure = re.search(r'class="stage-figure[^"]*".*?(?=<p class="caption">)', section.group(0), re.S)
            found = svgs(figure.group(0)) if figure else []
            if len(found) < 2:
                self.fail("fallback.figure", s, "static figure must exist in landscape and portrait")
            for layout, body in found:
                nodes = re.findall(r'data-node-id="(N\d\d)"', body)
                if len(nodes) != derived[s]["entity_count"] or len(nodes) != expectations[s]:
                    self.fail("fallback.entities", "%s %s" % (s, layout), "expected %d entities, found %d" % (derived[s]["entity_count"], len(nodes)))
                stubs = re.findall(r'data-kind="stub"', body)
                if s in ("S0", "S1", "S2", "S3") and len(stubs) != len(derived[s]["stub_relationship_ids"]):
                    self.fail("fallback.stubs", "%s %s" % (s, layout), "expected %d stubs, found %d" % (len(derived[s]["stub_relationship_ids"]), len(stubs)))
                if s == "S3":
                    labelled = sorted(re.findall(r'<text class="identifier"[^>]*>(N\d\d)</text>', body))
                    if labelled != anchors:
                        self.fail("fallback.anchors", "S3 %s" % layout, "anchors %s, expected %s" % (labelled, anchors))
        record = re.search(r'<figure class="transition-record".*?</figure>', raw, re.S)
        sides = svgs(record.group(0)) if record else []
        if len(sides) != 2:
            self.fail("fallback.record", "S5", "transition record must contain the lattice and the field")
        for layout, body in sides:
            nodes = sorted(re.findall(r'data-node-id="(N\d\d)"', body))
            labelled = sorted(re.findall(r'<text class="identifier"[^>]*>(N\d\d)</text>', body))
            if nodes != build_site_ids():
                self.fail("fallback.record", "S5 record", "all 24 entities required on both sides")
            if labelled != anchors:
                self.fail("fallback.record_anchors", "S5 record", "anchors %s, expected %s" % (labelled, anchors))
        if record and not re.search(r'<figcaption class="record-text">[^<]{40,}</figcaption>', record.group(0)):
            self.fail("fallback.record_text", "S5 record", "text equivalent missing")

    # -- Contrast and budgets ----------------------------------------------------

    def contrast(self):
        variables = css_variables(read_bytes(os.path.join(self.docs, "assets", "system.css")).decode("utf-8"))
        ratios = {}
        for fg, bg, minimum, use in CONTRAST_PAIRS:
            if fg not in variables or bg not in variables:
                self.fail("contrast.missing", fg, "color role not defined as a hex custom property")
                continue
            ratio = contrast(variables[fg], variables[bg])
            ratios[fg] = (variables[fg], round(ratio, 2), minimum, use)
            if ratio < minimum:
                self.fail("contrast.ratio", fg, "%.2f:1 below %.1f:1 for %s" % (ratio, minimum, use))
        self.report["colors"] = variables
        self.report["contrast"] = ratios

    def budgets(self):
        sizes = {}
        for name in ("index.html", "assets/system.js", "assets/system.css", "data/demonstration-fixture.json"):
            data = read_bytes(os.path.join(self.docs, name))
            sizes[name] = (len(data), gz(data))
        self.report["sizes"] = sizes
        js = sizes["assets/system.js"][1]
        first_view = sum(v[1] for v in sizes.values())
        self.report["first_view_gzip"] = first_view
        if js > JS_BUDGET:
            self.fail("budget.js", "assets/system.js", "%d compressed bytes exceeds %d" % (js, JS_BUDGET))
        if first_view > FIRST_VIEW_BUDGET:
            self.fail("budget.first_view", "first view", "%d compressed bytes exceeds %d" % (first_view, FIRST_VIEW_BUDGET))

    def public_safety(self):
        targets = [os.path.join(self.docs, "index.html"), os.path.join(self.docs, "assets", "system.js"),
                   os.path.join(self.docs, "assets", "system.css")]
        for base, _, names in os.walk(SRC):
            targets += [os.path.join(base, n) for n in sorted(names)]
        for path in targets:
            text = read_bytes(path).decode("utf-8")
            for pattern in PRIVATE_TERMS:
                if re.search(pattern, text, re.I):
                    self.fail("safety.private_term", os.path.relpath(path, REPO_ROOT), pattern)

    def run(self):
        if not os.path.isdir(self.docs):
            self.fail("structure.docs", self.docs, "missing")
            return self.failures
        self.generation()
        self.surface()
        self.structure()
        self.claims()
        self.fixture_integration()
        self.contrast()
        self.budgets()
        self.public_safety()
        return self.failures


def build_site_ids():
    return ["N%02d" % i for i in range(1, 25)]


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--docs", default=DOCS)
    parser.add_argument("--skip-build-check", action="store_true")
    args = parser.parse_args(argv[1:])
    v = SiteValidator(args.docs, build_check=not args.skip_build_check)
    failures = v.run()
    if failures:
        print("SITE INVALID: %d failure(s)" % len(failures))
        for f in failures:
            print("- [%s] %s: %s" % f)
        return 1
    print("SITE VALID: all checks pass")
    print("reference pages: %d  local links checked: %d" % (v.report["reference_pages"], v.report["local_links_checked"]))
    for name, (raw, compressed) in v.report["sizes"].items():
        print("%-34s %7d bytes  %6d gzip" % (name, raw, compressed))
    print("first view (gzip): %d bytes of %d budget" % (v.report["first_view_gzip"], FIRST_VIEW_BUDGET))
    for role, (value, ratio, minimum, use) in v.report["contrast"].items():
        print("%-26s %s  %5.2f:1 (min %.1f, %s)" % (role, value, ratio, minimum, use))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
